name: Build and Publish Rule Book

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

env:
  ARTIFACT_RETENTION_DAYS: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Compile rule book
        uses: xu-cheng/latex-action@v3
        with:
          extra_system_packages: "inkscape"
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          pre_compile: export HOMM3_GITHUB_BUILD=1
          root_file: main_en.tex

      - name: Find quote string
        id: quote
        run: |
          QUOTE=$(grep "intro" main_en.tex -A2 | tail -1 | awk '{$1=$1};1'| awk '{for(i=1;i<=4;i++) printf $i" "; print ""}')
          echo "quote=$QUOTE" >> $GITHUB_OUTPUT

      - name: Optimize PDF
        if: steps.cache-pdf.outputs.cache-hit != 'true'
        id: optimize
        uses: qwrtln/optimize-pdf@v1
        with:
          file-name: main_en.pdf
          output-file: en/main_en.pdf
          quality-level: prepress
          test-string: ${{ steps.quote.outputs.quote }}

      - uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: main_en
          path: en/main_en.pdf
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}

      - name: Publish ${{ matrix.language }} in artifacts repository
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY_BUILD_ARTIFACTS }}
          external_repository: qwrtln/Homm3BG-FactoryRulebook -build-artifacts
          publish_branch: en
          publish_dir: ./en
          force_orphan: true
